[phases.setup]
nixPkgs = ['go']

[phases.install]
cmds = [
  'go mod download',
  'go install github.com/a-h/templ/cmd/templ@v0.3.924'
]

[phases.build]
cmds = [
  '~/go/bin/templ generate ./internal/dashboard/views/',
  'GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -o golden-gate ./cmd/main.go'
]

[start]
cmd = './golden-gate'

[variables]
GO_ENV = 'production'
CGO_ENABLED = '0'
GOOS = 'linux'
GOARCH = 'arm64'

[static]
dirs = ["static"] 
