[phases.setup]
nixPkgs = ['go']

[phases.install]
cmds = [
  'go mod download',
  'go install github.com/a-h/templ/cmd/templ@latest'
]

[phases.build]
cmds = [
  '~/go/bin/templ generate ./internal/dashboard/views/',
  'go build -o golden-gate ./cmd/main.go'
]

[start]
cmd = './golden-gate'

[static]
dirs = ["static"] 